language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6dev"
  - "nightly"
  - "pypy"
  - "pypy3"
# command to install dependencies
before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

install:
 - "pip install -r dev_requirements.txt"
 - "pip install -e ."

# command to run tests
script: pytest

os:
  - linux

addons:
  apt_packages:
    - pandoc
