language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6dev"
  - "nightly"
  - "pypy"
  - "pypy3"
# command to install dependencies
before_install:
  - echo $PYTHONPATH

install:
 - "pip install -r dev_requirements.txt"
 - "pip install -e ."

after_install:
 - echo $PYTHONPATH
 - /usr/bin/env python -c 'import ascii_telnet'
 - /usr/bin/env python -c 'import ascii_telnet.lib.ascii_movie'
 - pwd

# command to run tests
script: pytest

os:
  - linux

addons:
  apt_packages:
    - pandoc
